### ISSUE TITLE
Infinite scroll jumping

### ISSUE THREAD

**Issue by robbyklein** [darkroomengineering/lenis#108]
Hey there,

I recently discovered Lenis from the article [here](https://tympanus.net/codrops/2023/01/11/getting-creative-with-infinite-loop-scrolling/). I was trying to get a basic scroll loop going just like the simple example code in the article. Problem is when I try it it keep's jumping, was wondering what's going wrong.

Here's a [codepen](https://codepen.io/robbyklein/full/yLqjWoe ) demonstrating the issue, and here's the code I'm using:

```js
const repeatItems = (parentEl, total = 0) => {
    const items = [...parentEl.children];
    for (let i = 0; i <= total-1; ++i) {
        var cln = items[i].cloneNode(true);
        parentEl.appendChild(cln);
    }
};

repeatItems(document.querySelector('.loop'), 5);

const lenis = new Lenis({
  smooth: true,
  infinite: true,
});

function raf(time) {
  lenis.raf(time);
  requestAnimationFrame(raf);
}

requestAnimationFrame(raf);
```

```html
<div class="loop">
  <div class="section red">1</div>
  <div class="section green">2</div>
  <div class="section yellow">3</div>
  <div class="section blue">4</div>
  <div class="section purple">5</div>
</div>
```

```scss
/* Reset not shown */

.section {
  height: 600px;
  line-height: 600px;
  text-align: center;
  font-weight: 900;
  color: white;
  font-size: 200px;
  
  &.red {
    background: red;
  }
  
  &.green {
    background: green;
  }
  
  &.yellow {
    background: yellow;
  }
  
  &.blue {
    background: blue;
  }
  
  &.purple {
    background: purple;
  }
}
```

Any help would be appreciated, thanks!
