### ISSUE TITLE
Mark `react` and `react-dom` peer dependencies as optional.

### ISSUE THREAD

**Issue by stefanobartoletti** [darkroomengineering/lenis#329]
I noticed that after upgrading to the latest versions from `1.0.42`, installing the base `lenis` also installs as new dependencies also those marked as peer, namely `react` and `react-dom`, that seem to be relevant only for the `react-lenis` package. Also, some other packages that seems only related to a React environment are pulled by default (i.e. Hamo and possibly others)

When using this library in other environments (i.e. I am using it with Vue and Nuxt), these dependencies should not be installed by default, and the optimal behavior should be previous one, as in `1.0.42` (only "plain" Lenis was installed).

If it matters, I'm having this behavior with `pnpm`

**Comment by clementroche** [comment]
Thank you for your feedback, what's the problem with having react, react-dom and hamo as dependencies since they will be tree-shaked anyway ? 

I added them as dependencies to be sure that lenis/react can be used without any extra config required. Perhaps I could set  react and react-dom as peerDependencies since it's obvious that you need them in order to use lenis/react.

**Comment by stefanobartoletti** [comment]
The fact is that even if these dependencies are not used, they still have to be resolved and downloaded.
This is not really optimal, both on local development and especially when deploying, you will end using more build minutes and bandwidth than what the application really requires

This also may force other project dependencies to resolve these if they have it as optional deps too, in example this is what happens to another package that I have in my project before and after upgrading Lenis:

```yaml
  '@tresjs/cientos':
    specifier: ^3.8.0
    version: 3.8.0(@tresjs/core@3.7.0)(three@0.163.0)(tweakpane@4.0.3)(vue@3.4.21)
```

```yaml
  '@tresjs/cientos':
    specifier: ^3.8.0
    version: 3.8.0(@tresjs/core@3.7.0)(react@18.2.0)(three@0.163.0)(tweakpane@4.0.3)(vue@3.4.21)
```

Of course it is up to you and how you feel it is the best way to manage the project, but a sensible way would be to not forcibly include what is not actually used or needed. 
Lenis in itself is a great tool and really works wonderfully, but another of its selling-points IMHO is that does wonders while also being a very lightweight package (not only in the final bundle but in the whole process) and that it had exactly 0 dependencies.

If you set them as peer dependencies, you can consider setting them as optional, by using the required properties in package.json.

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependenciesmeta
